// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class Account
{
    public string Id { get; set; }

    public string Email { get; set; }

    public DateOnly Dob { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public int? Status { get; set; }

    public string RoleId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public ulong? IsDeleted { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<Cart> CartAccounts { get; set; } = new List<Cart>();

    public virtual Cart CartIdNavigation { get; set; }

    public virtual ICollection<EmailToken> EmailTokens { get; set; } = new List<EmailToken>();

    public virtual Role Role { get; set; }

    public virtual ICollection<ShipmentHistory> ShipmentHistories { get; set; } = new List<ShipmentHistory>();

    public virtual Wallet Wallet { get; set; }

    public virtual ICollection<WalletHistory> WalletHistories { get; set; } = new List<WalletHistory>();

    public virtual ICollection<WithDrawForm> WithDrawForms { get; set; } = new List<WithDrawForm>();
}