// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class Promotion
{
    public string Id { get; set; }

    public string Event { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int? PercentageDiscountValue { get; set; }

    public decimal? DiscountValue { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public ulong? IsDeleted { get; set; }

    public virtual ICollection<ProductSet> ProductSets { get; set; } = new List<ProductSet>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}