// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class Transaction
{
    public string Id { get; set; }

    public string PaymentTypeId { get; set; }

    public ulong? PaymentLocation { get; set; }

    public DateOnly? PayDate { get; set; }

    public decimal? Amount { get; set; }

    public string Description { get; set; }

    public string TransactionStatusId { get; set; }

    public string WalletHistoryId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public ulong? IsDeleted { get; set; }

    public virtual Order IdNavigation { get; set; }

    public virtual TransactionStatus TransactionStatus { get; set; }

    public virtual WalletHistory WalletHistory { get; set; }
}