// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class Voucher
{
    public string Id { get; set; }

    public string VoucherName { get; set; }

    public decimal? VoucherDiscountAmount { get; set; }

    public ulong? IsDiscountPercentage { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int? Amount { get; set; }

    public decimal? MinOrderValue { get; set; }

    public decimal? MaxDiscountValue { get; set; }

    public ulong? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public ulong? IsDeleted { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}