// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class ProductSet
{
    public string Id { get; set; }

    public string ProductSetName { get; set; }

    public string Description { get; set; }

    public int? SetQuantity { get; set; }

    public int? Quantity { get; set; }

    public decimal? Price { get; set; }

    public string PromotionId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public ulong? IsDeleted { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual Promotion Promotion { get; set; }
}