// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class WithDrawForm
{
    public string Id { get; set; }

    public string Title { get; set; }

    public decimal Amount { get; set; }

    public string WithdrawStatusId { get; set; }

    public string AccountId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public ulong? IsDeleted { get; set; }

    public virtual Account Account { get; set; }

    public virtual WithdrawStatus WithdrawStatus { get; set; }
}