name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Bước xác thực AWS bắt buộc
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/randox:${{ github.sha }}
    
    # Bước tạo package được cải thiện
    - name: Generate deployment package
      run: |
        mkdir -p deploy
        # Kiểm tra xem file Dockerrun.aws.json có tồn tại không
        if [ ! -f src/RandoX.API/Dockerrun.aws.json ]; then
          echo "❌ Error: Dockerrun.aws.json not found!"
          exit 1
        fi
        cp src/RandoX.API/Dockerrun.aws.json deploy/
        cd deploy && zip -r ../deploy.zip .
        # Kiểm tra file zip đã được tạo
        if [ ! -f ../deploy.zip ]; then
          echo "❌ Error: deploy.zip creation failed!"
          exit 1
        fi
        ls -lh ../deploy.zip
    
    # Thêm bước debug để kiểm tra nội dung zip
    - name: Debug - Check zip contents
      run: |
        unzip -l deploy.zip
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: randox
        environment_name: randox-env
        version_label: ${{ github.sha }}
        region: ap-southeast-2
        deployment_package: deploy.zip
        # Thêm các tham số quan trọng
        wait_for_deployment: true
        verbose: true